baseURL = "https://laubergedesgourmets.com/"
languageCode = "fr-fr"
title = "L'Auberge des Gourmets"
theme = "ag"

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true

[menu]
  [[menu.main]]
		identifier = "homepage"
		name = "Restaurant"
		url = "/"
		weight = 1 

  [[menu.main]]
		identifier = "guillaume-laublanc"
		name = "Guillaume Laublanc"
		url = "/guillaume-laublanc/"
		weight = 2 

  [[menu.main]]
		identifier = "carte-menu"
		name = "Menu"
		url = "/carte-menu/"
		weight = 3

  [[menu.main]]
    identifier = "carte-menu-paques_2023"
    name = "Menu Saint Pâques 2023"
    url = "/carte-menu-paques_2023/"
    weight = 3


#  [[menu.main]]
#		identifier = "tourisme-tournus"
#		name = "Tourisme"
#		url = "/tourisme-tournus/"
#		weight = 4
#
#  [[menu.main]]
#		identifier = "producteurs"
#		name = "Producteurs"
#		url = "/producteurs/"
#		weight = 5

  [[menu.main]]
		identifier = "situation-contact"
		name = "Contact"
		url = "/situation-contact/"
		weight = 6
