baseURL = "https://laubergedesgourmets.zufrieden.io/"
languageCode = "fr-fr"
title = "L'Auberge des Groumets"
theme = "ag"

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true

[menu]
  [[menu.main]]
		identifier = "homepage"
		name = "L'Auberge des Gourmets"
		url = "/"
		weight = 1 

  [[menu.main]]
		identifier = "guillaume-laublanc"
		name = "Guillaume Laublanc"
		url = "/guillaume-laublanc/"
		weight = 2 

  [[menu.main]]
		identifier = "carte-menu"
		name = "Carte et Menu"
		url = "/carte-menu/"
		weight = 3

  [[menu.main]]
		identifier = "tourisme-tournus"
		name = "Tourisme dans les environs"
		url = "/tourisme-tournus/"
		weight = 4

  [[menu.main]]
		identifier = "producteurs"
		name = "Les producteurs"
		url = "/producteurs/"
		weight = 5

  [[menu.main]]
		identifier = "situation-contact"
		name = "Situation Contact"
		url = "/situation-contact/"
		weight = 6
